### ISSUE TITLE
can you use this with atom-hydra?

### ISSUE THREAD

**Issue by neo451** [arnoson/hydra-midi#13]
can you use this with atom-hydra?

**Comment by arnoson** [comment]
I don't use atom-hydra, feel free to try it and report any issues

**Comment by neo451** [comment]
I tried it and it reported error saying： await is only valid in async functions and the top level bodies of modules
ps: web hydra works fine for me

**Comment by arnoson** [comment]
Okay, than it may work using promise-syntax instead:

```js
// You can either use `@latest` or load a specific version with, for example, `@0.4.0`.
loadScript(
  'https://cdn.jsdelivr.net/npm/hydra-midi@latest/dist/index.js'
).then(() => {
  midi.start({ channel: '*', input: '*' })
  midi.show()
})

solid(note('*'), 0, 1).out()
```

**Comment by neo451** [comment]
thx for your quick response, tried it. no error message this time, but still errors when trying to use it, this time all the functions are not defined

**Comment by arnoson** [comment]
mhh, yes the functions outside of `then` aren't there yet. Maybe put everything inside `then`.
But in general hydra relies on the top-level `async` call to load external scripts, so I'm not sure if it will ever work 100% without it. I'm closing this since it is not a problem with this library but with atom-hydra, so you might open an issue there.

**Comment by neo451** [comment]
ok thank you for your response
